"""initial schema

Revision ID: 5ac095ef8bb7
Revises: 
Create Date: 2026-05-26 14:29:33.340137
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5ac095ef8bb7'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker', sa.String(length=32), nullable=False),
    sa.Column('account_label', sa.String(length=128), nullable=False),
    sa.Column('native_currency', sa.String(length=3), nullable=False),
    sa.Column('account_type', sa.String(length=16), nullable=True),
    sa.Column('opened_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.CheckConstraint("account_type IN ('brokerage','savings','cash')", name='ck_account_type'),
    sa.CheckConstraint("broker IN ('vanguard','fidelity','savings_bank')", name='ck_account_broker'),
    sa.CheckConstraint('length(native_currency) = 3', name='ck_account_currency_len'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_config',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('fx_history',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('base', sa.String(length=3), nullable=False),
    sa.Column('quote', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.CheckConstraint('length(base) = 3', name='ck_fx_base_len'),
    sa.CheckConstraint('length(quote) = 3', name='ck_fx_quote_len'),
    sa.PrimaryKeyConstraint('date', 'base', 'quote')
    )
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('asset_class', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('native_currency', sa.String(length=3), nullable=False),
    sa.Column('expense_ratio', sa.Numeric(precision=7, scale=5), nullable=True),
    sa.Column('target_weight_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("asset_class IN ('etf','mutual_fund','stock','cash','savings')", name='ck_instrument_asset_class'),
    sa.CheckConstraint('length(native_currency) = 3', name='ck_instrument_currency_len'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instruments_symbol'), ['symbol'], unique=True)

    op.create_table('target_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('price_history',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close_native', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id', 'date')
    )
    op.create_table('target_allocation_items',
    sa.Column('target_allocation_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('weight_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_allocation_id'], ['target_allocations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('target_allocation_id', 'instrument_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('price_native', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('gross_native', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('fees_native', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('net_native', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('fx_rate_to_eur', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('net_eur', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("kind IN ('buy','sell','dividend_cash','dividend_reinvest','deposit','withdrawal','interest','fee','transfer_in','transfer_out','split')", name='ck_transactions_kind'),
    sa.CheckConstraint("source IN ('import_vanguard_csv','import_fidelity_csv','manual','migration')", name='ck_transactions_source'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'external_id', name='uq_transactions_account_external')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transactions_account_date', ['account_id', 'date'], unique=False)
        batch_op.create_index('ix_transactions_date', ['date'], unique=False)
        batch_op.create_index('ix_transactions_instrument_id', ['instrument_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_instrument_id')
        batch_op.drop_index('ix_transactions_date')
        batch_op.drop_index('ix_transactions_account_date')

    op.drop_table('transactions')
    op.drop_table('target_allocation_items')
    op.drop_table('price_history')
    op.drop_table('target_allocations')
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruments_symbol'))

    op.drop_table('instruments')
    op.drop_table('fx_history')
    op.drop_table('app_config')
    op.drop_table('accounts')
    # ### end Alembic commands ###
